spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/nuti?authSource=admin
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  jpa:
    show-sql: true