CREATE DATABASE IF NOT EXISTS db;

USE db;

CREATE TABLE IF NOT EXISTS url(
    id BIGINT(100) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    url VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tag(
    id BIGINT(100) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    url_id BIGINT(100) NOT NULL,
    FOREIGN KEY (url_id) REFERENCES url(id),
    nome_tag VARCHAR(50) NOT NULL,
    quantidade INT(4) NOT NULL
);